
import '../../model/logedin_model.dart';

abstract class LoginState{}
 class IntiLoginState extends LoginState{}
 class LodingLoginState extends LoginState{}
 class ScLoginState extends LoginState{
  final Autogenerated loginModel;

  ScLoginState(this.loginModel);
 }
 class ErrorLoginState extends LoginState{
  final String error;
  ErrorLoginState(this.error);
 }
 class ChangeShowPass extends LoginState{}
 
 class LodingRegisteState extends LoginState{}
 class ScRegisteState extends LoginState{
  final Autogenerated loginModel;
  ScRegisteState(this.loginModel);
 }
 class ErrorRegisteState extends LoginState{
  final String error;
  ErrorRegisteState(this.error);
 }
 class ChangeShowPassRegiste extends LoginState{}


 class LodingGoogleSignIn extends LoginState{}
 class ScGoogleSignIn extends LoginState{
  //final Autogenerated loginModel;
  //ScGoogleSignIn(this.loginModel);
 }
 class ErrorGoogleSignIn extends LoginState{
  final String error;
  ErrorGoogleSignIn(this.error);
 }
 class LodingFaceBookleSignIn extends LoginState{}
 class ScFaceBookleSignIn extends LoginState{
  //final Autogenerated loginModel;
  //ScFaceBookleSignIn(this.loginModel);
 }
 class ErrorFaceBookleSignIn extends LoginState{
  final String error;
  ErrorFaceBookleSignIn(this.error);
 }

 class LodingLogeOut extends LoginState{}
 class ScLogeOut extends LoginState{
  //final Autogenerated loginModel;
  //ScLogeOut(this.loginModel);
 }
 class ErrorLogeOut extends LoginState{
  final String error;
  ErrorLogeOut(this.error);
 }


 class LodingForgetPass extends LoginState{}
 class ScForgetPass extends LoginState{}
 class ErrorForgetPass extends LoginState{
  final String error;
  ErrorForgetPass(this.error);
 }

 class LodingOTP extends LoginState{}
 class ScOTP extends LoginState{}
 class ErrorOTP extends LoginState{
  final String error;
  ErrorOTP(this.error);
 }

 class LodingResetPass extends LoginState{}
 class ScResetPass extends LoginState{}
 class ErrorResetPass extends LoginState{
  final String error;
  ErrorResetPass(this.error);
 }
 